Traceback (most recent call last):
  File "gan_train.py", line 110, in gan_train
    fake_images = G(bw_image)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/Patrick/Documents/Berkeley/2017-2018/Side Projects/Image Colorization/gan.py", line 60, in forward
    x = self.mp1(F.relu(self.bn1(self.conv1(x))))
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 277, in forward
    self.padding, self.dilation, self.groups)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/functional.py", line 85, in conv2d
    raise ValueError("Expected 4D tensor as input, got {}D tensor instead.".format(input.dim()))
ValueError: Expected 4D tensor as input, got 5D tensor instead.
